export function compileBatch(action) {
    let script = [];
    script.push("@echo off");
    script.push(":: Generated by Microart Menuify");
    script.push(":: DO NOT EDIT THIS FILE");

    // Menuify styling
    script.push(":: Custom styling");
    script.push("title Menuify - Running command");
    script.push("color 03");
    script.push("mode con: cols=100 lines=4");

    // script setup
    script.push("if exist %1% (");
    script.push("\tgoto okay");
    script.push(")");
    script.push("exit");
    script.push(":okay");
    script.push(`echo Running command '${action.info}', please wait...`);
    script.push(":: Menuify variables");
    script.push("set filename=%1%");
    script.push("set filenameWE=");
    script.push("for %%a in (%filename%) do (@set filenameWE=%%~na)");

    // command to execute
    script.push(action.command.replaceAll("{filename}", "%filename%").replaceAll("{filenameWE}", "%filenameWE%"));

    return script.join("\n");
}